### ISSUE TITLE
Erreur lié au chemin relatif des media

### ISSUE THREAD

**Issue by Shagshag** [grocanar/GedcomforGeneanet#3]
Erreur lors de l'export sous windows 7 avec Gramps 5.1.1

J'ai l'impression que c'est lié au chemin relatif des media
```
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'Documents\\Arbre généalogique\\Documents\\Actes\\Espagne\\AHPZ_A_003644 - Recensement électoral 1890 - Coscojuela de Sobrarbe - page 456 sur 1157.jpg'
```
Dans Edition > Paramètres > Général > Chemin de base pour les chemins relatifs des media il y a D:\ qui ne semble pas pris en compte dans l'export.

log complet :
```
246368: ERROR: _exportassistant.py: line 597: Erreur lors de l'exportation de votre arbre familial
Traceback (most recent call last):
  File "D:\AppData\Roaming\gramps\gramps51\plugins\GedcomforGeneanet\GedcomforGeneanet.py", line 1348, in export_data
    ret = ged_write.write_gedcom_file(filename)
  File "D:\AppData\Roaming\gramps\gramps51\plugins\GedcomforGeneanet\GedcomforGeneanet.py", line 1176, in write_gedcom_file
    self._individuals()
  File "C:\Program Files\GrampsAIO64-5.1.1\gramps\plugins\export\exportgedcom.py", line 411, in _individuals
    self._person(self.dbase.get_person_from_handle(data[1]))
  File "C:\Program Files\GrampsAIO64-5.1.1\gramps\plugins\export\exportgedcom.py", line 447, in _person
    self._person_event_ref('BIRT', person.get_birth_ref())
  File "D:\AppData\Roaming\gramps\gramps51\plugins\GedcomforGeneanet\GedcomforGeneanet.py", line 795, in _person_event_ref
    super(GedcomWriterforGeneanet, self)._person_event_ref(key,event_ref)
  File "C:\Program Files\GrampsAIO64-5.1.1\gramps\plugins\export\exportgedcom.py", line 1114, in _person_event_ref
    self._dump_event_stats(event, event_ref)
  File "D:\AppData\Roaming\gramps\gramps51\plugins\GedcomforGeneanet\GedcomforGeneanet.py", line 952, in _dump_event_stats
    self._source_references(event.get_citation_list(), 2)
  File "C:\Program Files\GrampsAIO64-5.1.1\gramps\plugins\export\exportgedcom.py", line 686, in _source_references
    self._source_ref_record(level, citation_handle)
  File "D:\AppData\Roaming\gramps\gramps51\plugins\GedcomforGeneanet\GedcomforGeneanet.py", line 1142, in _source_ref_record
    self._photos(citation.get_media_list(), level + 1)
  File "C:\Program Files\GrampsAIO64-5.1.1\gramps\plugins\export\exportgedcom.py", line 708, in _photos
    self._photo(photo, level)
  File "D:\AppData\Roaming\gramps\gramps51\plugins\GedcomforGeneanet\GedcomforGeneanet.py", line 699, in _photo
    self._packzip(path)
  File "D:\AppData\Roaming\gramps\gramps51\plugins\GedcomforGeneanet\GedcomforGeneanet.py", line 704, in _packzip
    self.zipfile.write(path)
  File "AIO/zipfile.py", line 1594, in write
  File "AIO/zipfile.py", line 484, in from_file
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'Documents\\Arbre généalogique\\Documents\\Actes\\Espagne\\AHPZ_A_003644 - Recensement électoral 1890 - Coscojuela de Sobrarbe - page 456 sur 1157.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.1\gramps\gui\plug\export\_exportassistant.py", line 593, in save
    self.option_box_instance)
  File "D:\AppData\Roaming\gramps\gramps51\plugins\GedcomforGeneanet\GedcomforGeneanet.py", line 1351, in export_data
    user.notify_error(msg2, msg)
  File "C:\Program Files\GrampsAIO64-5.1.1\gramps\gui\user.py", line 148, in notify_error
    self.error_function(title, error, parent=self.parent)
  File "C:\Program Files\GrampsAIO64-5.1.1\gramps\gui\dialog.py", line 263, in __init__
    self.format_secondary_text(msg2)
  File "AIO/gi/overrides/Gtk.py", line 590, in format_secondary_text
TypeError: Must be string, not FileNotFoundError
```

**Comment by grocanar** [comment]
Bonjour
Désole pour la reponse tardive. J'ai du mal a imaginer que des personnes utilisent mon code directement depuis github.
Helas sur ce probleme je ne sais trop que dire. je n'ai pas acces facilement a une machine windows.
Est ce que des rapports incluant des medias tels que

**Comment by TitiFix** [comment]
Bonjour Eric,
Je confirme le problème ce n'est spécifiquement lié à une machine Windows
dans le cas où les options "chemin relatif pour les médias" et "créer une archive zip des medias" sont sélectionnées 

cf Ligne 700 (en V2.0.12)  : la fonction self._packzip y est appelée avec un chemin relatif lorsque le zip des media est créé. Cela ne marche que si l'on est dans le bon répertoire. il faut utiliser une variable "fullpath"

Cordialement
Thierry

**Comment by grocanar** [comment]
Merci Thierry 
je vais regarder cela alors.
